// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egcbcywblhxdxpoetztd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnY2JjeXdibGh4ZHhwb2V0enRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTYwNjIsImV4cCI6MjA2OTQzMjA2Mn0.S2oWVX1EaRBNRzgvREH3UadHxmna1D90Mwwoxd3rlEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});